-- PHAN I:
-- cau 8:
ALTER TABLE SANPHAM 
ADD CONSTRAINT SANPHAM_GIA CHECK(GIA > 500)

--cau 9:
ALTER TABLE CTHD
ADD CONSTRAINT CTHD_SL CHECK(SL >= 1)

-- cau 10:
ALTER TABLE KHACHHANG
ADD CONSTRAINT KH_NGDK_NGSINH CHECK(NGDK >= NGSINH)



-- PHAN II:
-- cau 2:
SELECT * FROM SANPHAM,KHACHHANG 
-- cau 3: 
UPDATE SANPHAM SET GIA=GIA+GIA/(100/5) 
WHERE NUOCSX='SINGAPORE' 
-- cau 4:
UPDATE SANPHAM SET GIA =GIA/(100/5)+GIA 
WHERE NUOCSX='TRUNG QUOC' AND GIA >10000 




-- PHAN III
-- cau 1:
SELECT MASP,TENSP
FROM  SANPHAM
WHERE NUOCSX='TRUNG QUOC'

-- cau 2:
SELECT MASP,TENSP
FROM  SANPHAM
WHERE DVT='CAY' OR DVT='QUYEN'

-- cau 3:
SELECT MASP,TENSP
FROM  SANPHAM
WHERE MASP LIKE 'B%01'

-- cau 4:
SELECT MASP,TENSP
FROM  SANPHAM
WHERE NUOCSX='TRUNG QUOC' AND GIA BETWEEN 30000 AND 40000

-- cau 5:
SELECT MASP,TENSP
FROM  SANPHAM
WHERE (NUOCSX='TRUNG QUOC' OR NUOCSX='THAI LAN') AND GIA BETWEEN 30000 AND 

-- cau 6:
SELECT SOHD,TRIGIA
FROM  HOADON
WHERE NGHD='1/1/2007' OR NGHD='2/1/2007'

-- cau 7:
SELECT SOHD,TRIGIA
FROM  HOADON
WHERE MONTH(NGHD)=1 AND YEAR(NGHD)=2007
ORDER BY  NGHD ASC,TRIGIA DESC

-- cau 8:
SELECT A.MAKH,HOTEN
FROM  HOADON A, KHACHHANG B
WHERE A.MAKH=B.MAKH AND NGHD='1/1/2007'

-- cau 9:
SELECT SOHD,TRIGIA
FROM  HOADON A, NHANVIEN B
WHERE A.MANV=B.MANV AND NGHD='28/10/2006' AND HOTEN='NGUYEN VAN B' 

-- cau 10:
SELECT C.MASP, TENSP
FROM  HOADON A, KHACHHANG B, CTHD C, SANPHAM D
WHERE A.MAKH=B.MAKH AND A.SOHD=C.SOHD AND C.MASP=D.MASP AND
  MONTH(NGHD)=10 AND YEAR(NGHD)=2006 AND HOTEN='NGUYEN VAN A'



